name: Build Bookmarklets

on:
  push:
    paths:
      - 'main/bookmarklets/source/**'
  workflow_dispatch:

jobs:
  bookmarkletify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install minifier
        run: npm install -g terser

      - name: Transform to bookmarklets
        run: |
          mkdir -p main/bookmarklets/min
          for file in main/bookmarklets/source/*.js; do
            filename=$(basename "$file")
            minified=$(terser "$file" --compress --mangle)
            echo "javascript:$minified" > "main/bookmarklets/min/$filename"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add main/bookmarklets/min
          git commit -m "Automated bookmarkletify" || echo "No changes to commit"
          git push