name: Build Bookmarklets

on:
  push:
    branches:
        - main
    paths:
      - 'bookmarklets/source/**'
  workflow_dispatch:

jobs:
  bookmarkletify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install minifier
        run: npm install -g terser

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Transform to bookmarklets
        run: |
            mkdir -p bookmarklets/min
            shopt -s nullglob
            files=(bookmarklets/source/*.js)
            if [ ${#files[@]} -eq 0 ]; then
            echo "No .js files to process."
            exit 0
            fi

            for file in "${files[@]}"; do
            filename=$(basename "$file")
            minified=$(terser "$file" --compress --mangle)
            
            # Encode for bookmarklet safely
            encoded=$(printf '%s' "$minified" | jq -sRr @uri)

            echo "javascript:(function(){$encoded})();" > "bookmarklets/min/$filename"
            done


      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add bookmarklets/min
          git commit -m "Automated bookmarkletify" || echo "No changes to commit"
          git push